version: '3.7'

services:
  app:
    container_name: app
    image: app_image
    restart: always
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db
    hostname: db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    image: library/postgres:14.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=main
    volumes:
      - app_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app_redis:
    image: redis:6.2-alpine
    hostname: redis
    container_name: app_redis
    command:
      - 'redis-server'
    ports:
      - 6379:6379

volumes:
  app_pg_data:
    driver: "local"

networks:
  default:
    external: true
    name: app_main